### ISSUE TITLE
NPM load issue

### ISSUE THREAD

**Issue by zifeis** [codeit-ninja/SRT-Support-for-HTML5-videos#11]
From console
./node_modules/srt-support-for-html5-videos/src/track.js 20:5
Module parse failed: Unexpected token (20:5)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|    * @type {string}
|    */
>   src;
|   /**
|    * @readonly

From Chrome
main.js:12 Uncaught Error: Module parse failed: Unexpected token (22:8)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|    * @type {number}
|    */
>   number;
| 
|   /**
    at ./node_modules/srt-support-for-html5-videos/src/cue.js (main.js:12:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/srt-support-for-html5-videos/src/helpers.js (helpers.js:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at ./node_modules/srt-support-for-html5-videos/main.js (main.js:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (index.css?ee34:82:1)
    at ./src/slate-transcript-editor/src/components/index.js (index.js:805:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (index.js:28:1)
    at ./src/slate-transcript-editor/src/index.js (index.js:11:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (index.css?bb0a:82:1)
    at ./src/index.js (index.js:298:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at 1 (timecodeToSeconds.js:34:1)
    at __webpack_require__ (bootstrap:856:1)
    at checkDeferredModules (bootstrap:45:1)
    at Array.webpackJsonpCallback [as push] (bootstrap:32:1)
    at main.chunk.js:1:63

**Comment by codeit-ninja** [comment]
I will look into this issue

**Comment by codeit-ninja** [comment]
Do you have steps on how to reproduce this error? For example a github project where the error occurs?

**Comment by codeit-ninja** [comment]
Not responding, closing
